export { default as IcoHeart } from './IcoHeart'
export { default as Logo } from './Logo'
export { default as Order } from './Order'
export { default as SearchIcon } from './Search'
export { default as IcoFacebook } from './IcoFacebook'
export { default as IcoInstagram } from './IcoInstagram'
export { default as IcoTiktok } from './IcoTiktok'

export { default as IcoGoogle } from './IcoGoogle'
export { default as IcoApple } from './IcoApple'
export { default as IcoArrowRight } from './IcoArrowRight'
export { default as IcoSpin } from './IcoSpin'
export { default as IcoPhone } from './IcoPhone'
export { default as IcoStarFill } from './IcoStarFill'
export { default as IcoStarHalfFill } from './IcoStarHalfFill'
export { default as IcoStarEmpty } from './IcoStarEmpty'
export { default as IcoReviewBuy } from './IcoReviewBuy'
export { default as IcoEmptyBox } from './IcoEmptyBox'

export * from './Payments'
export * from './Accounts'
export * from './Navigation'
export * from './Reviews'
