// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >
  } & // Group
  {
    [TGroup in Extract<
      TRelationship['fields'][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship['fields'][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never
  }

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >
}[Exclude<TCustomType[number], string>['id']]

type BannerManagementDocumentDataSlicesSlice = CollectionBannerSlice

/**
 * Content for Banner Management documents
 */
interface BannerManagementDocumentData {
  /**
   * Slice Zone field in *Banner Management*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_management.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BannerManagementDocumentDataSlicesSlice>
}

/**
 * Banner Management document from Prismic
 *
 * - **API ID**: `banner_management`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BannerManagementDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BannerManagementDocumentData>,
    'banner_management',
    Lang
  >

/**
 * Item in *Homepage → Hero Banners*
 */
export interface HomepageDocumentDataHeroBannersItem {
  /**
   * Image field in *Homepage → Hero Banners*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_banners[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<'Mobile'>

  /**
   * Title field in *Homepage → Hero Banners*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_banners[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField

  /**
   * Lower Title field in *Homepage → Hero Banners*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_banners[].lower_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  lower_title: prismic.KeyTextField

  /**
   * Text field in *Homepage → Hero Banners*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_banners[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField

  /**
   * Title 2 field in *Homepage → Hero Banners*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_banners[].title_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_2: prismic.KeyTextField

  /**
   * Button Text field in *Homepage → Hero Banners*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_banners[].button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField

  /**
   * Pathname field in *Homepage → Hero Banners*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_banners[].pathname
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pathname: prismic.KeyTextField
}

/**
 * Item in *Homepage → Collections*
 */
export interface HomepageDocumentDataCollectionsItem {
  /**
   * Collection field in *Homepage → Collections*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.collections[].collection
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  collection: prismic.ImageField<'Mobile'>

  /**
   * Title Top field in *Homepage → Collections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.collections[].title_top
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_top: prismic.KeyTextField

  /**
   * Sub Title Top field in *Homepage → Collections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.collections[].sub_title_top
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sub_title_top: prismic.KeyTextField

  /**
   * Title Bottom field in *Homepage → Collections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.collections[].title_bottom
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_bottom: prismic.KeyTextField

  /**
   * Sub Title Bottom field in *Homepage → Collections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.collections[].sub_title_bottom
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sub_title_bottom: prismic.KeyTextField

  /**
   * Pathname field in *Homepage → Collections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.collections[].pathname
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pathname: prismic.KeyTextField

  /**
   * Button Text field in *Homepage → Collections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.collections[].button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField
}

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Hero Banners field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_banners[]
   * - **Tab**: Banner
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  hero_banners: prismic.GroupField<
    Simplify<HomepageDocumentDataHeroBannersItem>
  > /**
   * Collections field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.collections[]
   * - **Tab**: Collections
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  collections: prismic.GroupField<Simplify<HomepageDocumentDataCollectionsItem>>
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    'homepage',
    Lang
  >

export type AllDocumentTypes = BannerManagementDocument | HomepageDocument

/**
 * Item in *CollectionBanner → Default → Primary → Tile Banner*
 */
export interface CollectionBannerSliceDefaultPrimaryTileBannerItem {
  /**
   * Tile Banner Image field in *CollectionBanner → Default → Primary → Tile Banner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_banner.default.primary.tile_banner[].tile_banner_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  tile_banner_image: prismic.ImageField<'Mobile'>

  /**
   * Tile Banner Pathname field in *CollectionBanner → Default → Primary → Tile Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_banner.default.primary.tile_banner[].tile_pathame
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tile_pathame: prismic.KeyTextField

  /**
   * Tile Banner Button Label field in *CollectionBanner → Default → Primary → Tile Banner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_banner.default.primary.tile_banner[].tile_banner_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tile_banner_button_label: prismic.KeyTextField
}

/**
 * Item in *CollectionBanner → Default → Primary → Collection*
 */
export interface CollectionBannerSliceDefaultPrimaryCollectionItem {
  /**
   * Collection Pathname field in *CollectionBanner → Default → Primary → Collection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_banner.default.primary.collection[].collection_pathname
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  collection_pathname: prismic.KeyTextField
}

/**
 * Primary content in *CollectionBanner → Default → Primary*
 */
export interface CollectionBannerSliceDefaultPrimary {
  /**
   * Banner field in *CollectionBanner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_banner.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<'Mobile'>

  /**
   * Pathname field in *CollectionBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_banner.default.primary.pathname
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pathname: prismic.KeyTextField

  /**
   * Tile Banner field in *CollectionBanner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_banner.default.primary.tile_banner[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tile_banner: prismic.GroupField<
    Simplify<CollectionBannerSliceDefaultPrimaryTileBannerItem>
  >

  /**
   * Start Date field in *CollectionBanner → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_banner.default.primary.start_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  start_date: prismic.DateField

  /**
   * End Date field in *CollectionBanner → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_banner.default.primary.end_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  end_date: prismic.DateField

  /**
   * Collection field in *CollectionBanner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: collection_banner.default.primary.collection[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  collection: prismic.GroupField<
    Simplify<CollectionBannerSliceDefaultPrimaryCollectionItem>
  >

  /**
   * hidenz field in *CollectionBanner → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: collection_banner.default.primary.hidenz
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  hidenz: prismic.BooleanField

  /**
   * site field in *CollectionBanner → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: ALL
   * - **API ID Path**: collection_banner.default.primary.site
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  site: prismic.SelectField<'ALL' | 'AU' | 'NZ', 'filled'>
}

/**
 * Default variation for CollectionBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CollectionBannerSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CollectionBannerSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *CollectionBanner*
 */
type CollectionBannerSliceVariation = CollectionBannerSliceDefault

/**
 * CollectionBanner Shared Slice
 *
 * - **API ID**: `collection_banner`
 * - **Description**: CollectionBanner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CollectionBannerSlice = prismic.SharedSlice<
  'collection_banner',
  CollectionBannerSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>
  }

  namespace Content {
    export type {
      BannerManagementDocument,
      BannerManagementDocumentData,
      BannerManagementDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataHeroBannersItem,
      HomepageDocumentDataCollectionsItem,
      AllDocumentTypes,
      CollectionBannerSlice,
      CollectionBannerSliceDefaultPrimaryTileBannerItem,
      CollectionBannerSliceDefaultPrimaryCollectionItem,
      CollectionBannerSliceDefaultPrimary,
      CollectionBannerSliceVariation,
      CollectionBannerSliceDefault,
    }
  }
}
