// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  banner_test: dynamic(() => import('./BannerTest')),
  collection_banner: dynamic(() => import('./CollectionBanner')),
}
