import { GlobalUIProvider } from '@/components/common/Layout/GlobalUI'
import MainLayout from '@/components/common/Layout/MainLayout'
import ShopifyAnalyticsClient from '@/components/layout/Analytics'
import type { Metadata } from 'next'
import { Literata, Tangerine } from 'next/font/google'
import StoreProvider from '../components/common/Layout/StoreProvider'
import { primaryFont } from './font'
import './globals.css'
import MainScript from '@/components/common/MainScript'

const tangerineFont = Tangerine({
  variable: '--font-tangerine-sans',
  subsets: ['latin'],
  weight: ['400', '700'],
})

const literataFont = Literata({
  variable: '--font-literata-sans',
  subsets: ['latin'],
  weight: ['200', '700'],
})

export const metadata: Metadata = {
  title: 'Printwork',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${tangerineFont.variable} ${literataFont.variable} ${primaryFont.variable} antialiased`}
      >
        <StoreProvider>
          <GlobalUIProvider>
            <ShopifyAnalyticsClient />
            <MainLayout>{children}</MainLayout>
          </GlobalUIProvider>
        </StoreProvider>
        <MainScript />
      </body>
    </html>
  )
}
