// app/layout.tsx
import { Suspense } from 'react'
import { GlobalUIProvider } from '@/components/common/Layout/GlobalUI'
import MainLayout from '@/components/common/Layout/MainLayout'
import MainScript from '@/components/common/MainScript'
import StoreProvider from '@/components/common/Layout/StoreProvider'
import { repositoryName } from '@/prismicio'
import { PrismicPreview } from '@prismicio/next'
import type { Metadata } from 'next'
import { Literata, Tangerine } from 'next/font/google'
import { primaryFont } from './font'
import 'swiper/css'
import 'swiper/css/grid'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import './globals.css'

const tangerineFont = Tangerine({
  variable: '--font-tangerine-sans',
  subsets: ['latin'],
  weight: ['400', '700'],
})

const literataFont = Literata({
  variable: '--font-literata-sans',
  subsets: ['latin'],
  weight: ['200', '700'],
})

export const metadata: Metadata = {
  title: 'Printwork',
  description: 'Generated by create next app',
}

async function DynamicLayout({ children }: { children: React.ReactNode }) {
  return <RootLayoutContent>{children}</RootLayoutContent>
}

function RootLayoutContent({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${tangerineFont.variable} ${literataFont.variable} ${primaryFont.variable} antialiased`}
    >
      <body>
        <StoreProvider>
          <GlobalUIProvider>
            <MainLayout>{children}</MainLayout>
            <PrismicPreview repositoryName={repositoryName} />
          </GlobalUIProvider>
        </StoreProvider>
        <MainScript />
      </body>
    </html>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Suspense>
      <DynamicLayout>{children}</DynamicLayout>
    </Suspense>
  )
}
