// app/layout.tsx
import { GlobalUIProvider } from '@/components/common/Layout/GlobalUI'
import MainLayout from '@/components/common/Layout/MainLayout'
import StoreProvider from '@/components/common/Layout/StoreProvider'
import MainScript from '@/components/common/MainScript'
import { cookie } from '@prismicio/client'
import type { Metadata } from 'next'
import {
  Cormorant_Garamond,
  Open_Sans,
  Playfair_Display,
} from 'next/font/google'
import { cookies } from 'next/headers'
import { Suspense } from 'react'
import 'swiper/css'
import 'swiper/css/grid'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import './globals.css'

const SubHeadingFont = Cormorant_Garamond({
  variable: '--font-sub-heading',
  subsets: ['latin'],
  style: ['normal', 'italic'],
  weight: ['300', '400', '500', '600', '700'],
})

const HeadingFont = Playfair_Display({
  variable: '--font-heading',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

const ParagraphFont = Open_Sans({
  variable: '--font-paragraph',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Printwork',
  description: 'Generated by create next app',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'Printwork',
  },
}

async function PreviewLayout({ children }: { children: React.ReactNode }) {
  const cookiePreview = (await cookies()).get(cookie.preview)?.value
  return (
    <GlobalUIProvider>
      <Suspense>
        <MainLayout cookie={cookiePreview}>{children}</MainLayout>
      </Suspense>
    </GlobalUIProvider>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className={`${SubHeadingFont.variable} ${HeadingFont.variable} ${ParagraphFont.variable} antialiased`}
    >
      <body>
        <StoreProvider>
          <Suspense>
            <PreviewLayout>{children}</PreviewLayout>
          </Suspense>
        </StoreProvider>
        <MainScript />
      </body>
    </html>
  )
}
